config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get '/home',  to: 'static_pages#home'
  get '/about', to: 'static_pages#about'
  get '/signup', to: 'users#new'
  get '/employees', to: 'employees#index'
  get '/car_models', to: 'car_models#index'
  
  get '/add_car', to: 'car_models#new'
  post '/add_car', to: 'car_models#create'
  
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  
  resources :users
  resources :employees
  resources :car_models
  resources :sales
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/car_model.rb
class CarModel < ApplicationRecord
  has_many :sales
  validates :price, numericality: { only_integer: true }
  validates :brand, uniqueness: { scope: :model}
end

app/models/employee.rb
class Employee < ApplicationRecord
  has_many :users
  has_many :sales
  
  # Returns the sum that the employee has sold for
  def has_sold_for
    Sale.where(:employee_id => self.id).pluck(:car_model_id).map {|id| CarModel.find(id)}.pluck(:price).sum
  end
end

app/models/sale.rb
class Sale < ApplicationRecord
  belongs_to :employee
  belongs_to :car_model
  # Returns the sum of all sales.
  def Sale.sum_sales
    Sale.pluck(:car_model_id).map {|id| CarModel.find(id)}.pluck(:price).sum
  end
  
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token
  belongs_to :employee, optional: true
  before_save { email.downcase! }
  validates :name, presence: true, length: { maximum: 50}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
                    
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
 
  # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
  
  # Returns a random token.
  def User.new_token
    SecureRandom.urlsafe_base64
  end
  
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, remember_token)
  end
  
  # Returns true if the given token matches the digest.
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end
  
  # Forgets a user.
  def forget
    update_attribute(:remember_digest, nil)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/car_models_controller.rb
class CarModelsController < ApplicationController
  def new
    @car_model = CarModel.new
  end
  
  def index
    @car_models = CarModel.all
  end
  
  def destroy
    CarModel.find(params[:id]).destroy
    redirect_back(fallback_location: car_models_path)
  end
  
  def create
    @car_model = CarModel.new(car_model_params)
    if @car_model.save
      flash[:success] = "Added " + @car_model.brand + " " + @car_model.model
      redirect_to car_models_path
    else
      render 'new'
    end
  end
  
  private
  
    def car_model_params
        params.require(:car_model).permit(:brand, :model, :price)
    end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  def new
  end
  
  def index
    @employees = Employee.all
    @sales_sum = Sale.sum_sales
  end
  
  def show
      @employee = Employee.find(params[:id])
      @sales = Sale.where(employee_id: params[:id]) 
  end
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  def new
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      params[:session][:remember_me] == '1' ? remember(user) : forget(user)
      redirect_back_or user
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end
  
  def destroy
    log_out if logged_in?
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:edit, :update]
  before_action :correct_user,   only: [:edit, :update]
  
  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "Welcome to the Car Shop!"
      redirect_to @user
    else
      render 'new'
    end
  end
  
  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end
  
  private
  
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
    
    # Confirms a logged-in user.
    def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = "log in to access user edit page."
        redirect_to login_url
      end
    end
    
    # Confirms the correct user.
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless @user == current_user
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # Returns the full title on a per-page basis.
  def full_title(page_title = '')
    base_title = "Car Shop"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/car_models_helper.rb
module CarModelsHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  # Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end
  
  # Remembers a user in a persistent session.
  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end
  
  # Returns true if the given user is the current user.
  def current_user?(user)
    user == current_user
  end

  # Returns the user corresponding to the remember token cookie.
  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

  # Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_user.nil?
  end
  
  # Forgets a persistent session.
  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end
  
  # Logs out the current user.
  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end
  
  # Redirects to stored location (or to the default).
  def redirect_back_or(default)
    redirect_to(session[:forwarding_url] || default)
    session.delete(:forwarding_url)
  end

  # Stores the URL trying to be accessed.
  def store_location
    session[:forwarding_url] = request.original_url if request.get?
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/car_models/index.html.erb
<% provide(:title, "Car Models") %>
<h1>Car Models</h1>

<table class="item-table">
  <tr>
    <th>Model ID</th>
    <th>Brand</th>
    <th>Model</th>
    <th>Price</th>
    <th></th>
  </tr>
   <% @car_models.each do |car_model| %>
    <tr>
      <td><%=car_model.id %></td>
      <td><%=car_model.brand %></td>
      <td><%=car_model.model %></td>
      <td><%=car_model.price %></td>
      <td>   <%= link_to 'Delete Car', car_model, method: :delete,
                                     data: { confirm: 'This will permanently delete this care model. \n Are you sure?' } %> </td>
    </tr>
  <% end %>
</table>

<%= link_to "Add Car", add_car_path, class: "btn btn-block btn-primary" %>

app/views/car_models/new.html.erb
<% provide(:title, 'Add Car Model') %>
<h1>Add Car Model</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@car_model) do |f| %>
      <%= render 'shared/error_messages', :obj => @car_model %>

      <%= f.label :brand %>
      <%= f.text_field :brand, class: 'form-control' %>
      
      <%= f.label :model %>
      <%= f.text_field :model, class: 'form-control' %>

      <%= f.label :price %>
      <%= f.number_field :price, class: 'form-control' %>

      <%= f.submit "Add Car Model", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/employees/index.html.erb
<% provide(:title, "Employees") %>
<h1>Employees</h1>
<table class="item-table">
  <tr>
    <th>Employee ID</th>
    <th>Name</th>
  </tr>
   <% @employees.each do |employee| %>
    <tr>
      <td><a><%= link_to employee.id, employee %></a></td>
      <td><a></a><%= link_to employee.name, employee %></a></td>
    </tr>
  <% end %>
</table>
<div class=sales-sum-text><%= "Total sales revenue: " + @sales_sum.to_s %></div>

app/views/employees/new.html.erb
<h1>Employees#new</h1>
<p>Find me in app/views/employees/new.html.erb</p>

app/views/employees/show.html.erb
<% provide(:title, @employee.name) %>
<h3>Employee</h3>
<div class="profile-card">
  <%=image_tag("default_person.png", alt: "Employee", width: 100)%>
  <h1><%= @employee.name %></h1>
  <p class="profile-title">User</p>
  <p><%= "Revenue: " +  (@employee != nil ? @employee.has_sold_for.to_s : "") %></p>
</div>

<h1>Sales </h1>
<table class="item-table">
  <tr>
    <th>Model ID</th>
    <th>Brand</th>
    <th>Model</th>
    <th>Price</th>
  </tr>
   <% @sales.pluck(:car_model_id).map {|id| CarModel.find(id)}.each do |sale| %>
    <tr>
      <td><%= sale.id %></td>
      <td><%= sale.brand %></td>
      <td><%= sale.model %></td>
      <td><%= sale.price %></td>
    </tr>
  <% end %>
</table>
<div class=sales-sum-text><%= "Sales revenue: " + @employee.has_sold_for.to_s %></div>

app/views/layouts/_footer.html.erb
<footer class="footer">
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Car Shop", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "About", about_path %></li>
        <li><%= link_to "Car Models", car_models_path %></li>
        <li><%= link_to "Employees", employees_path %></li>
        <% if logged_in? %>
          <!--<li><%= link_to "Users", '#' %></li>-->
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/sales/new.html.erb
<h1>Sales#new</h1>
<p>Find me in app/views/sales/new.html.erb</p>

app/views/shared/_error_messages.html.erb
<% if obj.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(obj.errors.count, "error") %>.
    </div>
    <ul>
    <% obj.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1>About</h1>
<p>This is a simple demo of a car shop web app.</p>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
  <h1>Car Shop</h1>
  <h2>
    Welcome to the car shop.
  </h2>
    <%= link_to "New Account", signup_path, class: "btn btn-lg btn-primary" %>
</div>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>Update your profile</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', :obj => @user %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Save changes", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', :obj => @user %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>

<h3>Profile</h3>
<div class="profile-card">
  <%=image_tag("default_person.png", alt: "User", width: 100)%>
  <h1><%= @user.name %></h1>
  <p class="profile-title">User</p>
  <p></p>
</div>

<h3> <%= @user.employee != nil ? "Your salesperson: " : "You have no associated salesperson" %></h3>
  
<% unless @user.employee == nil %>

<div class="profile-card">
  <%=image_tag("default_person.png", alt: "User", width: 100)%>
  <h1><%= @user.employee.name %></h1>
  <p class="profile-title">Employee</p>
  <p><%= "Revenue: " +  (@user.employee != nil ? @user.employee.has_sold_for.to_s : "") %></p>

  <p><button class="profile-button" onclick=<%= "location.href='/employees/" + @user.employee.id.to_s + "'" %>>Profile</button></p>
</div>
<% end %>